### ISSUE TITLE
Procedure names auto-labeled incorrectly when symbols fail to resolve

### ISSUE THREAD

**Issue by leechristensen** [googleprojectzero/sandbox-attacksurface-analysis-tools#75] opened 2024-02-22 08:28 UTC
**Observation:**
When symbols fail to resolve for a binary, `Get-RpcServer` appears to assign RPC procedure names incorrectly:
![image](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/assets/5449193/fe504852-35d8-401b-abc6-c4e459abd213)

Tested with the latest code on Github as well as the version of NtObjectManager in the PSGallery. Confirmed that the symbol does not exist with symchk as well (can't grab it via [winbindex](https://winbindex.m417z.com/?file=spoolsv.exe) either).

**Expected outcome:**
If symbol resolution fails, assign an out-generated procedure name (e.g., `Proc0`, `Proc1`, `Proc2`, etc.).  Might also throw a warning if symbols are configured but no symbols were found.

Link to example binary (hash `C391E5024F1B8FAB6DCD88BBE3B36F71FAE02DD815EA9273D9ACB247781955FB`): [spoolsv.exe.txt](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/files/14370798/spoolsv.exe.txt)

**Comment by tyranid** [comment] 2024-02-22 08:46
Yeah this is "expected behavior" in a way. The symbol resolver is falling back to export symbols for the binary and so just returns mostly nonsensical names. This is why the `-IgnoreSymbols` parameter exists, to turn of symbol resolving so that you always get back the autogenerated values. I could look at filtering out export symbols I guess, as 99% I'm sure the RPC methods are not going to be exported from the binary.

**Comment by tyranid** [comment] 2024-02-22 09:05
Turns out I had code to fix this, and I just never enabled it :)

**Closed** 2024-02-22 09:05 UTC

**Comment by leechristensen** [comment] 2024-02-22 09:10
Works like a charm! Thank you!
